### ISSUE TITLE
brew install twilio fails with "sha256 mismatch" for 3.0.1 and 3.0.0

### ISSUE THREAD

**Issue by elpargo** [twilio/homebrew-brew#30]
Seems like the commit from today messed something up (I'm not familiar with brew recipes but this error seems to be in this package. 

After running the official command to install on a fresh machine.

`> brew tap twilio/brew && brew install twilio
`

**it fails with the following:**

`==> Downloading https://twilio-cli-prod.s3.amazonaws.com/twilio-v3.0.0/twilio-v3.0.0.tar.gz
######################################################################## 100.0%
Error: twilio: SHA256 mismatch
Expected: 4c782ad761787431e52f4696607613d9ca0bd291c25a7d64abef4dae54a98f5f
  Actual: 8789f1d314ed4bd7c7081d4424fba24fdaa897850d8691a3c78fb8ebc10f5893
    File: <........>/45a315176cccb12f81d583aa48418dd236d5406a603b7420323dffdc269360fc--twilio-v3.0.0.tar.gz
To retry an incomplete download, remove the file above.
`

Testing this over the terminal proofs the point the file currently being downloaded has the right checksum:

`> openssl sha256 twilio-v3.0.0.tar.gz
SHA256(twilio-v3.0.0.tar.gz)= 8789f1d314ed4bd7c7081d4424fba24fdaa897850d8691a3c78fb8ebc10f5893
`

Conclusion either the file or the sha256 signature is wrong. I believe it's the signature.

**Comment by charan678** [comment]
Thanks for reporting this issue.

This issue has been resolved [Fix](https://github.com/twilio/homebrew-brew/pull/31/files)

**Comment by elpargo** [comment]
Great stuff. it's fixed.

NOTE: I had to brew untap and then rerun brew tap for it to pick up the new versions.
